<?php

namespace Intranet\IntraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PointageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointageRepository extends EntityRepository
{
}
