parameters:
#    intranet_intra.example.class: Intranet\IntraBundle\Example

services:
#    intranet_intra.example:
#        class: %intranet_intra.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
